### ISSUE TITLE
GitLeaks - HashiCorp Terraform password field

### ISSUE THREAD

**Issue by SkyDevSecOps-SCMA** [sky-uk/ReactiveAPI#36]
Locations:<br><ul><li><a href='https://github.com/sky-uk/ReactiveAPI/blob/9526aab7a866ed4380d56acc9bde56655adb1630/TokenAuthenticationDemo/server/index.js#L7-L8'>TokenAuthenticationDemo/server/index.js</a></li></ul>

**Comment by skybordolie** [comment]
This is a false positive because we use the string `password = "password"` as a fake password for the demo. There's no sensitive and real password in this code
